import { writable, readable } from 'svelte/store';

const STORAGE_KEY = 'nutriplan-user';

function safeReadLocalUser() {
	try {
		const raw = window.localStorage.getItem(STORAGE_KEY);
		return raw ? JSON.parse(raw) : null;
	} catch(err) {
		console.error("Error leyendo el usuario: ", err)
		return null
	}
}

function createInternalStore() {

	const initial = typeof window !== 'undefined' ? safeReadLocalUser() : null;

	const _store = writable(initial);

	if (typeof window !== undefined) {
		_store.subscribe(val => {
			try {
				if(val) {
					window.localStorage.setItem(STORAGE_KEY, JSON.stringify(val))
				} else {
					window.localStorage.removeItem(STORAGE_KEY)
				}
			} catch(err) {
				console.error("Error guardando datos del usuario: ", err)
			}
		});
	}

	return _store
}

const _internalUserStore = createInternalStore()

export const authUser = {
	subscribe: _internalUserStore.subscribe
}

function talkToServer(email, password) {
	return new Promise((resolve) => {
		setTimeout(() => {
			// Communicate with the server

			// Return the session token
			return {user: 'Felipe', session_token: 'SKAJDOASDNUIU'}
		}, 1000)
	})	
}

export function mockSignUp({ name, email, password, phone }) {
	return new Promise((resolve) => {
		setTimeout(() => {
			const user = {
				name,
				email,
				phone,
				plan: 'NutriPlan Free',
				memberSince: new Intl.DateTimeFormat('es-NI', {
					month: 'long',
					year: 'numeric'
				}).format(new Date()),
				timezone: 'GMT-6 Managua',
				photo: null,
				preferences: {
					diet: 'Omnívora',
					autoGenerated: true
				},
				credentials: {
					password
				}
			};
			authUser.login(user);
			resolve(user);
		}, 1000);
	});
}

export function mockLogin({ email, password }) {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			try {
				_internalUserStore.set({ name: 'Dani', email: email})
				resolve('Dani')
			} catch(err) {
				reject(err)
			}
		}, 800);
	});
}

export function logout() {
	_internalUserStore.set(null)
}