import { writable } from 'svelte/store';

const STORAGE_KEY = 'nutriplan-user';

function createAuthStore() {
	const { subscribe, set, update } = writable(null);

	if (typeof window !== 'undefined') {
		try {
			const stored = window.localStorage.getItem(STORAGE_KEY);
			if (stored) {
				set(JSON.parse(stored));
			}
		} catch (error) {
			console.error('Error leyendo datos de usuario', error);
		}

		subscribe((value) => {
			try {
				if (value) {
					window.localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
				} else {
					window.localStorage.removeItem(STORAGE_KEY);
				}
			} catch (error) {
				console.error('Error guardando datos de usuario', error);
			}
		});
	}

	return {
		subscribe,
		set,
		update,
		login: (user) => set(user),
		logout: () => set(null)
	};
}

export const authUser = createAuthStore();

export function mockSignUp({ name, email, password, phone }) {
	return new Promise((resolve) => {
		setTimeout(() => {
			const user = {
				name,
				email,
				phone,
				plan: 'NutriPlan Free',
				memberSince: new Intl.DateTimeFormat('es-NI', {
					month: 'long',
					year: 'numeric'
				}).format(new Date()),
				timezone: 'GMT-6 Managua',
				photo: null,
				preferences: {
					diet: 'Omnívora',
					autoGenerated: true
				},
				credentials: {
					password
				}
			};
			authUser.login(user);
			resolve(user);
		}, 1000);
	});
}

export function mockLogin({ email, password }) {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			if (typeof window === 'undefined') {
				reject(new Error('Operación no disponible'));
				return;
			}

			const stored = window.localStorage.getItem(STORAGE_KEY);
			if (!stored) {
				reject(new Error('No encontramos una cuenta con ese correo.'));
				return;
			}

			try {
				const user = JSON.parse(stored);
				if (user.email === email && user.credentials?.password === password) {
					authUser.login(user);
					resolve(user);
				} else {
					reject(new Error('Credenciales incorrectas.'));
				}
			} catch (error) {
				reject(new Error('No se pudo leer la información de la cuenta.'));
			}
		}, 800);
	});
}

export function logout() {
	authUser.logout();
}
