# type: ignore[reportCallIssue]
# Generated by Django 5.2.5 on 2025-10-06 01:09

from decimal import Decimal
import uuid

from django.conf import settings
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.utils.timezone

import nutriplan.models.user


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("friendly_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["friendly_name"],
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["friendly_name"],
                        name="gin_trgm_category_name",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="nutriplan.dietaryrestriction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", nutriplan.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "calories_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=7
                    ),
                ),
                (
                    "protein_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "carbs_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "fat_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "sugar_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="nutriplan.dietaryrestriction",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(help_text="Short description shown prominently."),
                ),
                (
                    "main_image_url",
                    models.URLField(blank=True, help_text="Primary recipe image."),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time (in minutes)",
                        verbose_name="Prep Time",
                    ),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cooking time (in minutes)",
                        verbose_name="Cook Time",
                    ),
                ),
                (
                    "total_time",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("prep_time"), "+", models.F("cook_time")
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                ("servings", models.PositiveSmallIntegerField(default=1)),
                (
                    "calories_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="kcal per serving",
                        max_digits=8,
                    ),
                ),
                (
                    "total_calories",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Coalesce(
                                models.F("calories_per_serving"), 0
                            ),
                            "*",
                            django.db.models.functions.comparison.Coalesce(
                                models.F("servings"), 0
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=8
                        ),
                    ),
                ),
                (
                    "protein_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams protein per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "carbs_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams carbs per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "fat_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams fat per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "sugar_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams sugar per serving",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="nutriplan.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_collections",
                        to="nutriplan.recipe",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutriplan.recipecollection",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uses",
                        to="nutriplan.image",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_images",
                        to="nutriplan.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="nutriplan.RecipeImage",
                to="nutriplan.image",
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_recipes",
                        to="nutriplan.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="nutriplan.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="nutriplan.RecipeIngredient",
                to="nutriplan.ingredient",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="idx_user_email_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uniq_user_email_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"],
                name="gin_trgm_ingredient_desc",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="gin_trgm_ingredient_name",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("calories_per_100g__gte", 0)),
                name="chk_ing_cal_ge_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("protein_per_100g__gte", 0)),
                name="chk_ing_pro_ge_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("carbs_per_100g__gte", 0)), name="chk_ing_carb_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("fat_per_100g__gte", 0)), name="chk_ing_fat_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("sugar_per_100g__gte", 0)), name="chk_ing_sug_ge_0"
            ),
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="idx_collection_owner_name_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                models.F("owner"),
                models.F("created_at"),
                name="idx_collection_owner_created",
            ),
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                django.db.models.functions.text.Lower("slug"),
                name="idx_collection_slug_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecollection",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="uniq_collection_name_per_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecollection",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("slug"),
                name="uniq_collection_slug_per_owner_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["collection", "order", "id"], name="idx_collectionitem_order"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["recipe"], name="idx_collectionitem_recipe"),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "recipe"), name="uniq_collection_recipe"
            ),
        ),
        migrations.AddIndex(
            model_name="recipeimage",
            index=models.Index(
                fields=["recipe", "order", "id"], name="idx_recipeimage_rec_ord"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeimage",
            constraint=models.UniqueConstraint(
                fields=("recipe", "image"), name="unique_recipe_image"
            ),
        ),
        migrations.AddIndex(
            model_name="recipeingredient",
            index=models.Index(fields=["ingredient"], name="idx_ri_ingredient"),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="chk_ri_amount_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"],
                name="idx_recipe_desc_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="idx_recipe_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["category"], name="nutriplan_r_categor_4a1269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["created_at"], name="nutriplan_r_created_d54d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["slug"], name="idx_recipe_slug"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["total_time"], name="nutriplan_r_total_t_a4b924_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("prep_time__gte", 0)), name="chk_rec_prep_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("cook_time__gte", 0)), name="chk_rec_cook_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__gte", 0)), name="chk_rec_serv_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uniq_recipe_slug_ci",
            ),
        ),
    ]
