# Generated by Django 5.2.5 on 2025-10-01 23:21

from decimal import Decimal

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("friendly_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["friendly_name"],
            },
        ),
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="nutriplan.dietaryrestriction",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "calories_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=7
                    ),
                ),
                (
                    "protein_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "carbs_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "fat_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "sugar_per_100g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=6
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="nutriplan.dietaryrestriction",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.TextField(help_text="Short description shown prominently."),
                ),
                (
                    "main_image_url",
                    models.URLField(blank=True, help_text="Primary image URL"),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time (in minutes)",
                        verbose_name="Prep Time",
                    ),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cooking time (in minutes)",
                        verbose_name="Cook Time",
                    ),
                ),
                ("servings", models.PositiveSmallIntegerField(default=1)),
                (
                    "calories_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="kcal per serving",
                        max_digits=7,
                    ),
                ),
                (
                    "protein_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams protein per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "carbs_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams carbs per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "fat_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams fat per serving",
                        max_digits=6,
                    ),
                ),
                (
                    "sugar_per_serving",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(0),
                        help_text="grams sugar per serving",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="nutriplan.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uses",
                        to="nutriplan.image",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_images",
                        to="nutriplan.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="nutriplan.RecipeImage",
                to="nutriplan.image",
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_recipes",
                        to="nutriplan.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="nutriplan.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="nutriplan.RecipeIngredient",
                to="nutriplan.ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeimage",
            constraint=models.UniqueConstraint(
                fields=("recipe", "image"), name="unique_recipe_image"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
