# Generated by Django 5.2.5 on 2025-09-21 20:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='nutriplan.dietaryrestriction'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories_per_serving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='kcal per serving', max_digits=7),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs_per_serving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='grams carbs per serving', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat_per_serving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='grams fat per serving', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Primary image URL'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein_per_serving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='grams protein per serving', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar_per_serving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='grams sugar per serving', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Short description shown prominently.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='nutriplan.RecipeIngredient', to='nutriplan.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='nutriplan.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='nutriplan.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='nutriplan.image'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='nutriplan.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='nutriplan.RecipeImage', to='nutriplan.image'),
        ),
        migrations.AddConstraint(
            model_name='recipeimage',
            constraint=models.UniqueConstraint(fields=('recipe', 'image'), name='unique_recipe_image'),
        ),
    ]
