# Generated by Django 5.2.5 on 2025-10-09 17:55

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("google", "Google")], max_length=32),
                ),
                ("provider_user_id", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("avatar_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_user_id"], name="idx_provider_uid"
                    ),
                    models.Index(fields=["user"], name="idx_social_user"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="uniq_provider_uid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["google"])),
                        name="chk_valid_provider",
                    ),
                ],
            },
        ),
    ]
