# Generated by Django 5.2.5 on 2025-10-05 19:42

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_collections",
                        to="nutriplan.recipe",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutriplan.recipecollection",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="idx_collection_owner_name_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                models.F("owner"),
                models.F("created_at"),
                name="idx_collection_owner_created",
            ),
        ),
        migrations.AddIndex(
            model_name="recipecollection",
            index=models.Index(
                django.db.models.functions.text.Lower("slug"),
                name="idx_collection_slug_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecollection",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("name"),
                name="uniq_collection_name_per_owner_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecollection",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("slug"),
                name="uniq_collection_slug_per_owner_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["collection", "order", "id"], name="idx_collectionitem_order"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["recipe"], name="idx_collectionitem_recipe"),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "recipe"), name="uniq_collection_recipe"
            ),
        ),
    ]
