# Generated by Django 5.2.5 on 2025-10-02 10:55

from django.db import migrations, models

import nutriplan.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", nutriplan.models.user.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
