# Generated by Django 5.2.5 on 2025-09-09 01:30

from django.db import migrations

# Define your enum values here
CATEGORIES = [
    {"name": "BEEF", "friendly_name": "Beef"},
    {"name": "DAIRY_FREE", "friendly_name": "Dairy-Free"},
    {"name": "GLUTEN_FREE", "friendly_name": "Gluten-Free"},
    {"name": "HIGH_CARB", "friendly_name": "High-Carb"},
    {"name": "KETO", "friendly_name": "Keto"},
    {"name": "LOW_CARB", "friendly_name": "Low-Carb"},
    {"name": "VEGAN", "friendly_name": "Vegan"},
    {"name": "VEGETARIAN", "friendly_name": "Vegetarian"},
]


def add_categories(apps, schema_editor):
    Category = apps.get_model("nutriplan", "Category")
    for cat_data in CATEGORIES:
        Category.objects.get_or_create(
            name=cat_data["name"], defaults={"friendly_name": cat_data["friendly_name"]}
        )


def remove_categories(apps, schema_editor):
    Category = apps.get_model("nutriplan", "Category")
    for cat_data in CATEGORIES:
        Category.objects.filter(name=cat_data["name"]).delete()


class Migration(migrations.Migration):
    dependencies = [("nutriplan", "0001_initial")]

    operations = [
        migrations.RunPython(add_categories, remove_categories),
    ]
