# Generated by Django 5.2.5 on 2025-10-10 04:29

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0002_socialaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="nutriplan.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["recipe"], name="idx_review_recipe"),
                    models.Index(fields=["user"], name="idx_review_user"),
                    models.Index(fields=["rating"], name="idx_review_rating"),
                    models.Index(fields=["created_at"], name="idx_review_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe"), name="uniq_review_user_recipe"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="chk_rating_1_5",
                    ),
                ],
            },
        ),
    ]
