# Generated by Django 5.2.5 on 2025-10-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriplan', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recipes_m2m', to='nutriplan.category'),
        ),
    ]
