# Generated by Django 5.2.5 on 2025-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0005_backfill_categories"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recipe",
            name="nutriplan_r_categor_4a1269_idx",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="nutriplan.category"
            ),
        ),
    ]
