# Generated by Django 5.2.5 on 2025-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0006_remove_recipe_nutriplan_r_categor_4a1269_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(
                blank=True, help_text="Detailed step-by-step instructions."
            ),
        ),
    ]
