# Generated by Django 5.2.5 on 2025-10-16 16:45

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0007_recipe_instructions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="uniq_ing_name"
            ),
        ),
    ]
