# Generated by Django 5.2.5 on 2025-10-17 11:55

import uuid

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("nutriplan", "0009_chatthread_chatmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "title"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleRecipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_text", models.CharField(blank=True, max_length=180)),
                ("first_index", models.CharField(blank=True, max_length=24)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_refs",
                        to="nutriplan.article",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_refs",
                        to="nutriplan.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                through="nutriplan.ArticleRecipe",
                to="nutriplan.recipe",
            ),
        ),
        migrations.AddIndex(
            model_name="articlerecipe",
            index=models.Index(
                fields=["article", "recipe"], name="idx_article_recipe_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="articlerecipe",
            constraint=models.UniqueConstraint(
                fields=("article", "recipe"), name="uniq_article_recipe_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "created_at"], name="idx_article_author_created"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                django.db.models.functions.text.Lower("slug"),
                name="idx_article_slug_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="gin_trgm_article_title",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text"],
                name="gin_trgm_article_text",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uniq_article_slug_ci",
            ),
        ),
    ]
